services:
  postgres:
    container_name: postgres-backend-masterclass
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - database
    restart: unless-stopped
  redis:
    container_name: redis-backend-masterclass
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/root/redis
      - redis-volume:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=root
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

networks:
  database:
    driver: bridge

volumes:
  postgres:
  redis-volume:
